### ISSUE TITLE
How to configuration DB

### ISSUE THREAD

**Issue by nishantmonapara** [mesibo/messenger-app-backend#10]
Hi @mesibo team,
I have configured New APK code & New Back End code,
There is missing database configuration file in Backend code,

How can i connect Back-end & DB,
Please help me to figure it out.
Hopping positive response,

Thanks.
Nishant.

**Comment by mesibo** [comment]
messenger backend does not require any DB. Configure your app token here and host the backend

https://github.com/mesibo/messenger-app-backend/blob/master/mesiboconfig.php

If you need on-premise to store your messages, it is explained here https://mesibo.com/documentation/on-premise/ 

However, before using on-premise, first, finish your app using the cloud.
