### ISSUE TITLE
Mesibo on premise instance error

### ISSUE THREAD

**Issue by jemliF** [mesibo/messenger-app-backend#3]
Hi,
I have created an on premise with cloud fallback on Mesibo Dashboard. I have this error

> E0909-071021-955 (32): Query Error: delete from notifications where expiry < current_timestamp
> error Table 'cioforum.notifications' doesn't exist (1146 42S02)
> (failures 3235)

Always being displayed in Mesibo docker container logs.
Any help will be appreciated.

**Comment by mesibo** [comment]
This appears to be a network issue within your container. Can you send us the complete logs from the start?

Also,
1) Are you getting any database error? 
2) Can you check your database and see that the table 'notifications' is created.

**Comment by jemliF** [comment]
Thank you for your reply,

I can notice the creation of three tables: users, members and pushtokens. The notofications table was not created.

Here is the logs of my Mesibo container:

> E0809-131213-805 (1): Unable to open /proc/sys/kernel/core_pattern (truncate 1)
> E0809-131213-806 (1): PID: 1
> E0809-131213-820 (1): Local IP Address: 172.17.0.2
> E0809-131214-194 (10): TLS Certificate Path: /certs
> **C**0809-131214-194 (10): Unable to load certificate: /certs/cert.pem
> E0809-131214-309 (10): Generating self-signed TLS certificate for 157.245.128.181
> E0809-131214-522 (1): Mesibo On-Premise App ID: 6035
> I0809-131214-522 (1): Starting mesibo
> E0809-131214-527 (1): Query Error: CREATE TABLE IF NOT EXISTS notifications ( id bigint(20) unsigned NOT NULL AUTO_INCREMENT, uid int(10) unsigned DEFAULT '0', src int(10) unsigned DEFAULT '0', expiry timestamp NOT NULL DEFAULT '0000-00-00 00:00:00', updated timestamp NOT NULL DEFAU$
> error Invalid default value for 'expiry' (1067 42000)
> (failures 1)
> E0809-131214-528 (1): Query Error: CREATE TABLE IF NOT EXISTS groups ( gid int(10) unsigned NOT NULL AUTO_INCREMENT, aid int(10) unsigned NOT NULL DEFAULT '0', name varchar(64) DEFAULT '', lastactive timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, expiry timestamp NOT NULL DEFAULT '00$
> error Invalid default value for 'expiry' (1067 42000)
> (failures 1)
> E0809-131224-533 (32): Query Error: delete from notifications where expiry < current_timestamp
> error Table 'cioforum.notifications' doesn't exist (1146 42S02)
> (failures 2)
> E0809-131234-534 (32): Query Error: delete from notifications where expiry < current_timestamp
> error Table 'cioforum.notifications' doesn't exist (1146 42S02)
> (failures 2)
> E0809-131244-535 (32): Query Error: delete from notifications where expiry < current_timestamp
> error Table 'cioforum.notifications' doesn't exist (1146 42S02)
> (failures 3)
> E0809-131254-536 (32): Query Error: delete from notifications where expiry < current_timestamp
> error Table 'cioforum.notifications' doesn't exist (1146 42S02)
> (failures 3)
> E0809-131304-537 (32): Query Error: delete from notifications where expiry < current_timestamp
> error Table 'cioforum.notifications' doesn't exist (1146 42S02)

By the way I am using Mysql 5.7 database on the same machine.

**Comment by mesibo** [comment]
You have not granted all the permission to your database user and hence mesibo on-premise server is not able to write anything to your database. Ensure to grant all the permissions and run again. Something like, 

     GRANT ALL ON dbname.* TO 'dbusername'@'localhost' identified by dbusername';

**Comment by mesibo** [comment]
Are you running your MySQL in the strict mode? It appears to have an issue with timestamp filed in strict mode and we will fix it asap. In the meantime, if you can, disable strict mode or create notifications table manually. 

```
CREATE TABLE IF NOT EXISTS notifications (
  id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  uid int(10) unsigned DEFAULT '0',
  src int(10) unsigned DEFAULT '0',
  expiry timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  n varbinary(32768) DEFAULT '',
  sent tinyint(4) DEFAULT '0',
  UNIQUE KEY id_2 (id,uid),
  KEY uid (uid),
  KEY expiry (expiry),
  KEY sent (sent)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```

**Comment by jemliF** [comment]
The errors disappeared when I disabled strict mode and it creates 5 tables in Mysql database.
Thanks
