### ISSUE TITLE
Database error starting mesibo docker image

### ISSUE THREAD

**Issue by ronadjom** [mesibo/messenger-app-backend#6]
Hi,

i followed all the instructions described on page [https://mesibo.com/documentation/on-premise/#step-2---download-mesibo-on-premise-platform](https://mesibo.com/documentation/on-premise/#step-2---download-mesibo-on-premise-platform) for installing an onpremise instance of mesibo.

I had difficulties getting it started due to tables that were not created. So i had to create the tables but i had no idea of the table names and columns names and type. So i found out this schema [https://github.com/mesibo/messenger-app-backend/blob/master/mysql-schema.sql](https://github.com/mesibo/messenger-app-backend/blob/master/mysql-schema.sql) i then used to create all tables.
I then started the instance and most of the errors disappeared but one keep on showing:
```
I0205-232815-859 (1): Starting mesibo
E0205-232815-860 (1): Query Error: update pushtokens set tid=0 where push=0
error Table 'mesibo.pushtokens' doesn't exist (1146 42S02)
(failures 1)
E0205-232815-861 (1): creating database
E0205-232815-930 (1): ==> ready to connect users now!
```

Now my questions:
1. What is the schema of the table "pushtokens"?
2. Why do i need to install these tables my self?
3. Why is this not documented? If it is, please provide the actual link so i can install all the tables in case some might be missing still.

**Comment by mesibo** [comment]
Disable MySQL strict mode and restart.

Also, this is not the right repository to get support for on-premise, Raise a ticket from mesibo.com/ticket if you still have an issue.,
