### ISSUE TITLE
Issue facing with ssl/tls certificate for mesibo on-premises

### ISSUE THREAD

**Issue by Apurv-P** [mesibo/messenger-app-backend#9]
Hello,

I have Setup mesibo On-premises on my server and it is running with apache 80/443 (letsencrypt)
i have followed all the Steps mentioned in Documentation 

docker server logs like

Unable to open /proc/sys/kernel/core_pattern (truncate 1)
E2307-100158-656 (1): starting mesibo
E2307-100158-657 (1): PID: 1
E2307-100158-658 (1): build date: Wed Jul  1 07:08:08 2020 UTC
E2307-100158-658 (1): build number: 2518
E2307-100158-658 (1): module_exports_init
E2307-100158-658 (1): Local IP count: 2
E2307-100158-658 (1): --> multiple(2) IPs found - listening on all the IPs. If you like to use particular IPs only, set them in configuration using one or more 'ip' fields
E2307-100158-667 (1): signal ignored: 17
E2307-100158-667 (1): Local IP Address: server lP
E2307-100158-667 (1): Local IP Address: 172.17.0.1
E2307-100159-021 (12): TLS Certificate Path: /certs
**C**2307-100159-022 (12): Unable to load certificate: /certs/cert.pem
E2307-100159-054 (12): Generating self-signed TLS certificate for domain.com
E2307-100159-084 (12): syncing dbts
E2307-100159-120 (1): Mesibo On-Premise App ID: 8676
I2307-100159-120 (1): Starting mesibo
E2307-100159-121 (1): Query Error: update users set regaddr=0, lastonline=1595498519 where regaddr in (285971663,16781740)
error Unknown column 'regaddr' in 'where clause' (1054 42S22)
(failures 1)
E2307-100159-121 (1): creating database
E2307-100159-123 (1): ==> ready to connect users now!
E2307-100159-123 (26): Bind Failure - Server IP:80 (Address already in use)
**C**2307-100159-123 (26): socket failed for: Server IP:80 type 0
E2307-100159-123 (26): Bind Failure - Server IP:443 (Address already in use)
**C**2307-100159-123 (26): socket failed for: Server IP:443 type 0
E2307-100159-123 (26): Bind Failure - Server IP:80 (Address already in use)
**C**2307-100159-123 (26): socket failed for: Server IP:80 type 0
E2307-100159-123 (26): Bind Failure - Server IP:443 (Address already in use)
**C**2307-100159-123 (26): socket failed for: Server IP:443 type 0
E2307-100200-125 (28): Query Error: select a.id, a.aid, a.uid, a.channel, a.type, a.expiry, a.flag, a.gid, a.src, u.address, message from apimessages a, users u where a.src=u.uid and a.ts <= unix_timestamp() order by a.ts asc;
error Unknown column 'u.address' in 'field list' (1054 42S22)
(failures 1)
E2307-100209-984 (26): *** PERFORMANCE WARNING: your database has high latency 759 ms ***
E2307-100329-249 (26): *** PERFORMANCE WARNING: your database has high latency 759 ms ***
E2307-100452-973 (26): *** PERFORMANCE WARNING: your database has high latency 759 ms ***
E2307-100603-172 (26): *** PERFORMANCE WARNING: your database has high latency 1025 ms ***
E2307-100726-978 (26): *** PERFORMANCE WARNING: your database has high latency 1025 ms ***
E2307-100827-978 (26): *** PERFORMANCE WARNING: your database has high latency 1219 ms ***
E2307-100936-980 (26): *** PERFORMANCE WARNING: your database has high latency 1219 ms ***
E2307-101038-995 (26): *** PERFORMANCE WARNING: your database has high latency 1219 ms ***
E2307-101208-985 (26): *** PERFORMANCE WARNING: your database has high latency 1430 ms ***
E2307-101323-981 (26): *** PERFORMANCE WARNING: your database has high latency 1430 ms ***
E2307-101443-091 (26): *** PERFORMANCE WARNING: your database has high latency 1583 ms ***
E2307-101605-981 (26): *** PERFORMANCE WARNING: your database has high latency 1583 ms ***

Error getting in Firefox and Chrome web application in inspect element

mesibo.js:65 WebSocket connection to 'wss://www.domain:5443/' failed: Error in connection establishment: 
net::ERR_CERT_AUTHORITY_INVALID 

Certificate are Vaild and Active, still there are issue with cert auth

*some Lines are hidden in question

Please assist to fix this

Thanks

**Comment by mesibo** [comment]
Can not help you with hidden lines. Get in touch at https://mesibo.com/help if you have anything confidential

**Comment by saurabh8410** [comment]
Hi, Team

Database was successfully created but still unable to load the certificate.
Please help out with this as soon as possible. thanks in advance.
Here is the complete log of container

E1810-071725-818 (1): Unable to open /proc/sys/kernel/core_pattern (truncate 1)
E1810-071725-818 (1): starting mesibo
E1810-071725-818 (1): PID: 1
E1810-071725-819 (1): build date: Tue Oct 13 15:58:51 2020 UTC
E1810-071725-819 (1): build number: 2798
E1810-071725-819 (1): module_exports_init
E1810-071725-819 (1): Reading configuration file /etc/mesibo/mesibo.conf
E1810-071725-819 (1): Local IP count: 3
E1810-071725-819 (1): --> multiple(3) IPs found - listening on all the IPs. If you like to use particular IPs only, set them in configuration using one or more 'ip' fields
E1810-071725-832 (1): signal ignored: 17
E1810-071725-832 (1): Local IP Address: IP_address
E1810-071725-832 (1): Local IP Address: IP_address
E1810-071725-832 (1): Local IP Address: IP_address
E1810-071726-250 (12): certificate path: /etc/letsencrypt/live/domain_name
**C**1810-071726-251 (12): Unable to load certificate: /etc/letsencrypt/live/domain_name/cert.pem
E1810-071726-416 (12): Generating self-signed TLS certificate for <IP_address>
E1810-071726-446 (12): syncing dbts
E1810-071726-535 (1): Mesibo On-Premise App ID: <ID>
I1810-071726-535 (1): Starting mesibo
E1810-071726-539 (1): ==> ready to connect users now!
